# .github/ISSUE_TEMPLATE/task.yml
# ISSUE FORM: TASK（自動返信）
# VERSION: v0.2.0-issuebot-details-01
# BUILD(JST): 2025-12-14 13:58
name: "TASK（自動返信）"
description: "Botが要旨＋次の1アクションを返します（画像だけでもOK）"
title: "[TASK] "
labels: ["task"]
body:
  - type: textarea
    id: purpose
    attributes:
      label: "目的（1行）"
      description: "例）コピペ量を減らして、次の作業が迷いなく進むようにする"
      placeholder: "目的を1行で"
    validations:
      required: false

  - type: textarea
    id: request
    attributes:
      label: "依頼内容（やりたいこと）"
      description: "箇条書きでOK。画像だけでもOK（空欄可）"
      placeholder: "〜したい\n〜を確認したい"
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: "背景／状況（必要なら）"
      description: "前提・制約・いま困っていること（短く）"
      placeholder: "例）Issue返信の形式を固定したい"
    validations:
      required: false

  - type: textarea
    id: images
    attributes:
      label: "画像添付（任意）"
      description: "ここにスクショ画像をドラッグ＆ドロップ／貼り付け（Ctrl+V）でOK（複数OK）"
      placeholder: "ここに画像をドロップ（または貼り付け）"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **注意**
        - 秘密情報（APIキー等）は貼らないでください。
        - 承認は「Issue作成後のコメント欄」に `/approve` と書いてください（次工程へ進める合図）。
