name: "TASK（自動返信）"
description: "Botが要旨と次の1アクションを返します"
labels: ["task"]
title: "[TASK] "
body:
  - type: textarea
    id: purpose
    attributes:
      label: "目的（1行）"
      description: "例）コピペ量を減らして、次の作業が迷いなく進むようにする"
      placeholder: "目的を1行で"
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: "背景／状況（必要なら）"
      description: "前提・制約・いま困っていること（短く）"
      placeholder: "例）Issue返信の形式を固定したい"
      render: markdown
    validations:
      required: false

  - type: textarea
    id: request
    attributes:
      label: "依頼内容（やりたいこと）"
      description: "箇条書きでOK"
      placeholder: "- 〜したい\n- 〜を確認したい"
      render: markdown
    validations:
      required: false

  - type: textarea
    id: images
    attributes:
      label: "画像添付（任意）"
      description: "ここにスクショ画像をドラッグ＆ドロップ、または貼り付けしてOK（無理ならIssue作成後のコメント欄に添付でOK）"
      placeholder: "ここに画像をドロップ（または貼り付け）"
      render: markdown
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **注意：APIキーなど秘密情報は貼らないでください。**
  - type: markdown
    attributes:
      value: |
        ✅ 承認は「Issue作成後のコメント欄」に **/approve** と書いてください（それでRexへ自動で投げます）。
