name: "TASK（自動返信）"
description: "Botが要旨と次の1アクションを返します（画像だけでもOK）"
title: "[TASK] "
labels: ["task"]

body:
  - type: markdown
    attributes:
      value: |
        ✅ **画像だけでもOK**（本文は空欄でも作成できます）
        - 画像は下の「画像添付（任意）」に **ドラッグ＆ドロップ** または **貼り付け（Ctrl+V）**
        - 作成後、承認するならコメント欄に **/approve**
        - 注意：APIキーなどの秘密情報は貼らないでください

  - type: textarea
    id: purpose
    attributes:
      label: "目的（1行）"
      description: "例）コピペ量を減らして、次の作業が迷いなく進むようにする"
      placeholder: "目的を1行で（空欄OK）"
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: "背景／状況（必要なら）"
      description: "前提・制約・いま困っていること（短く）"
      placeholder: "例）Issue返信の形式を固定したい"
    validations:
      required: false

  - type: textarea
    id: request
    attributes:
      label: "依頼内容（やりたいこと）"
      description: "箇条書きでOK（空欄でも作成できます）"
      placeholder: |
        〜したい
        〜を確認したい
    validations:
      required: false

  - type: textarea
    id: images
    attributes:
      label: "画像添付（任意）"
      description: "ここにスクショ画像をドラッグ＆ドロップ／貼り付け（Ctrl+V）OK（複数OK）"
      placeholder: "ここに画像をドロップ（または貼り付け）"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ✅ 承認は「Issue作成後のコメント欄」に **/approve** と書いてください（それでRexへ投げる合図にします）。
