name: "TASK（自動返信）"
description: "Botが「要旨＋次の1アクション」を返します（空欄OK）"
title: "[TASK] "
labels: ["task"]

body:
  - type: textarea
    id: purpose
    attributes:
      label: "目的（1行）"
      description: "例）コピー量を減らして、次の作業が迷いなく進むようにする"
      placeholder: "目的を1行で（空欄でもOK）"
    validations:
      required: false

  - type: textarea
    id: request
    attributes:
      label: "依頼内容（やりたいこと）"
      description: "箇条書きでOK（空欄でもOK）"
      placeholder: "〜したい\n〜を確認したい"
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: "背景／状況（必要なら）"
      description: "前提・制約・いま困っていること（短く／空欄でもOK）"
      placeholder: "例）Issue返信の形式を固定したい"
    validations:
      required: false

  - type: textarea
    id: images
    attributes:
      label: "画像添付（任意）"
      description: "ここにスクショ画像をドラッグ＆ドロップ / 貼り付け（Ctrl+V）OK（複数OK）"
      placeholder: "ここに画像をドロップ（または貼り付け）"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **注意**
        - APIキー等の秘密情報は貼らないでください。
        - 承認して次へ進めるときは、コメント欄に **/approve** と書いてください（それでRexへ自動で投げます）。
