# .github/ISSUE_TEMPLATE/task.yml
name: "TASK（自動返信）"
description: "Botが『要旨＋次の1アクション』を返します"
title: "[TASK] "
labels: ["task"]

body:
  - type: textarea
    id: purpose
    attributes:
      label: "目的（1行）"
      description: "例）コピー量を減らして、次の作業が迷いなく進むようにする"
      placeholder: "（空欄OK）"
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: "背景／状況（必要なら）"
      description: "前提・制約・いま困っていること（短く）"
      placeholder: "例）Issue返信の形式を固定したい"
    validations:
      required: false

  - type: textarea
    id: request
    attributes:
      label: "依頼内容（やりたいこと）"
      description: "箇条書きでOK（空欄OK）"
      placeholder: |
        - 〜したい
        - 〜を確認したい
    validations:
      required: false

  - type: textarea
    id: images
    attributes:
      label: "画像添付（任意）"
      description: "この枠にスクショ画像をドラッグ＆ドロップ／貼り付け（Ctrl+V）でOK（複数OK）"
      placeholder: "ここに画像をドロップ（または貼り付け）"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ✅ **承認**：Issue作成後のコメント欄に `/approve` と書く（それでRexへ自動で投げます）  
        ⚠️ **注意**：APIキーなど秘密情報は貼らないでください
