name: "TASK（自動返信）"
description: "Botが要旨と次の1アクションを返します"
title: "[TASK] "
labels: ["task"]
body:
  - type: textarea
    id: purpose
    attributes:
      label: 目的（1行）
      description: 例）コピペ量を減らして、次の作業が迷いなく進むようにする
      placeholder: 目的を1行で
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 背景／状況（必要なら）
      description: いま困っていること・前提条件など
      placeholder: 例）Issue返信の形式を固定したい
    validations:
      required: false

  - type: textarea
    id: request
    attributes:
      label: やりたいこと（箇条書きでOK）
      description: Botに返してほしい観点もここに書く
      placeholder: |
        - こうしたい
        - これを自動化したい
    validations:
      required: true

  - type: textarea
    id: constraints
    attributes:
      label: 制約（あれば）
      description: 例）秘密情報は書かない／1アクションで進めたい など
      placeholder: 例）APIキーなどは書かない
    validations:
      required: false
